name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #copy file to virtual machine
    - name: Checkout code
      uses: actions/checkout@v4

    #install java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    #execute the build file 
    - name: Build with Gradle
      run: gradle build 

    #keep version of build file
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/**

    #run gradle test
    - name: Run Unit Test
      run: gradle test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: build/reports/tests/**
        
    - name: Generate code coverage report
      run: gradle jacocoTestReport

    #upload all the file to github
    - name: Upload code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/html/**
        
    - name: Run Deployment
      run: java -jar build/libs/hello-world-java-V1.jar

